"""add sessions session_seats orders tickets

Revision ID: 77d4b31df22c
Revises: 267dc33b8288
Create Date: 2026-08-18 13:08:58.157377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d4b31df22c'
down_revision: Union[str, None] = '267dc33b8288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('sale_open_at', sa.DateTime(), nullable=False),
    sa.Column('sale_close_at', sa.DateTime(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_movie_id'), 'sessions', ['movie_id'], unique=False)
    op.create_index(op.f('ix_sessions_start_at'), 'sessions', ['start_at'], unique=False)
    op.create_index(op.f('ix_sessions_venue_id'), 'sessions', ['venue_id'], unique=False)
    op.create_index('ix_sessions_venue_start', 'sessions', ['venue_id', 'start_at'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_no'), 'orders', ['order_no'], unique=True)
    op.create_index(op.f('ix_orders_session_id'), 'orders', ['session_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('session_seats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('col_no', sa.Integer(), nullable=False),
    sa.Column('seat_no', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('lock_order_id', sa.Integer(), nullable=True),
    sa.Column('lock_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lock_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'row_no', 'col_no', name='uq_session_seat_position')
    )
    op.create_index(op.f('ix_session_seats_session_id'), 'session_seats', ['session_id'], unique=False)
    op.create_index('ix_session_seats_session_status', 'session_seats', ['session_id', 'status'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('session_seat_id', sa.Integer(), nullable=False),
    sa.Column('purchaser_user_id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('transfer_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('checked_in_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['purchaser_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['session_seat_id'], ['session_seats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_seat_id')
    )
    op.create_index(op.f('ix_tickets_order_id'), 'tickets', ['order_id'], unique=False)
    op.create_index('ix_tickets_owner_status', 'tickets', ['owner_user_id', 'status'], unique=False)
    op.create_index(op.f('ix_tickets_owner_user_id'), 'tickets', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_tickets_session_id'), 'tickets', ['session_id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_session_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_owner_user_id'), table_name='tickets')
    op.drop_index('ix_tickets_owner_status', table_name='tickets')
    op.drop_index(op.f('ix_tickets_order_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index('ix_session_seats_session_status', table_name='session_seats')
    op.drop_index(op.f('ix_session_seats_session_id'), table_name='session_seats')
    op.drop_table('session_seats')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_session_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_no'), table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_sessions_venue_start', table_name='sessions')
    op.drop_index(op.f('ix_sessions_venue_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_start_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_movie_id'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
