"""add transfer_records

Revision ID: a10e336f9884
Revises: 70d75a2dca46
Create Date: 2026-08-18 13:23:03.044751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a10e336f9884'
down_revision: Union[str, None] = '70d75a2dca46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_records_from_user_id'), 'transfer_records', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_transfer_records_ticket_id'), 'transfer_records', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_transfer_records_to_user_id'), 'transfer_records', ['to_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_records_to_user_id'), table_name='transfer_records')
    op.drop_index(op.f('ix_transfer_records_ticket_id'), table_name='transfer_records')
    op.drop_index(op.f('ix_transfer_records_from_user_id'), table_name='transfer_records')
    op.drop_table('transfer_records')
    # ### end Alembic commands ###
